import type { NextPage } from 'next'
import Head from 'next/head'
import GuestContainer from 'containers/Guest'

const Home: NextPage = () => {
  return (
    <>
       <Head>
            <title>Landing Page Container</title>
            <meta name='description' content='generated by create next app' />
            <link rel='icon' href='/favicon.ico'/>

        </Head>
        <GuestContainer />
    </>
  )
}

export default Home
